### ISSUE TITLE
PHP Error on Shaarli 10.2

### ISSUE THREAD

**Issue by 14ngr15t** [kalvn/Shaarli-Material#90] opened 2019-01-11 19:45 UTC
Installed your theme 10.2-patch2 and it works fine except on the permalink page I see this error at the top:

( ! ) Notice: Undefined variable: index_url in E:\Ampps\www\shaarli\tmp\includes.c04e6db3e3da5484d981ebaa00b75abc.rtpl.php on line 24 Call Stack #TimeMemoryFunctionLocation 10.0088722632{main}( )...\index.php:0 20.06303061336renderPage( )...\index.php:1866 30.06443108864showLinkList( )...\index.php:1549 40.06613156840PageBuilder->renderPage( )...\index.php:497 50.06613156840RainTPL->draw( )...\PageBuilder.php:188 60.06663219088include( 'E:\Ampps\www\shaarli\tmp\linklist.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php' )...\rain.tpl.class.php:175 70.06663221080RainTPL->draw( )...\linklist.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php:3 80.06693244232include( 'E:\Ampps\www\shaarli\tmp\includes.c04e6db3e3da5484d981ebaa00b75abc.rtpl.php' )...\rain.tpl.class.php:175 ?1CDE2Q" />

Any idea what is causing that?

**Comment by kalvn** [comment] 2019-01-12 09:43
What version of Shaarli do you use? Do you have the same problem with the default theme?

**Comment by 14ngr15t** [comment] 2019-01-12 20:36
Latest version (10.2) of Shaarli.  The default theme works fine with no errors.  It's just on this theme.  Thanks!

**Comment by kalvn** [comment] 2019-01-12 22:05
Thanks for the details. I was able to reproduce and fix the issue. You'll find the fix in [v0.10.2-patch.3](https://github.com/kalvn/Shaarli-Material/releases/tag/v0.10.2-patch.3).

Please let me know if it fine for you.

**Comment by kalvn** [comment] 2019-01-21 16:32
@14ngr15t did you managed to find out what was the issue?

**Comment by 14ngr15t** [comment] 2019-01-21 19:42
Unfortunately not.  I tried a fresh install like you said, and the same
thing happened.  I have just been using the default theme.

Thanks for the help, not sure what else to do!

**Comment by kalvn** [comment] 2019-01-21 19:50
That's unfortunate :(

I'll keep investigating and let you know if I find something.

**Comment by 14ngr15t** [comment] 2019-01-21 23:42
Thank you so much!

**Comment by iGormilhit** [comment] 2019-01-25 11:37
I encounter the same issue as soon as I set material as a theme:


[:error] [pid 3617] [client 46.229.168.136:59278] PHP Fatal error:  Uncaught Error: Call to undefined function thumbnail() in /var/www/shaarli/tmp/linklist.aeadca0864f49f08401fb0f97c162898.rtpl.php:93\nStack trace:\n#0 /var/www/shaarli/inc/rain.tpl.class.php(175): include()\n#1 /var/www/shaarli/application/PageBuilder.php(188): RainTPL->draw('linklist')\n#2 /var/www/shaarli/index.php(497): PageBuilder->renderPage('linklist')\n#3 /var/www/shaarli/index.php(916): showLinkList(Object(PageBuilder), Object(LinkDB), Object(Shaarli\\Config\\ConfigManager), Object(PluginManager), Object(Shaarli\\Security\\LoginManager))\n#4 /var/www/shaarli/index.php(1866): renderPage(Object(Shaarli\\Config\\ConfigManager), Object(PluginManager), Object(LinkDB), Object(History), Object(Shaarli\\Security\\SessionManager), Object(Shaarli\\Security\\LoginManager))\n#5 {main}\n  thrown in /var/www/shaarli/tmp/linklist.aeadca0864f49f08401fb0f97c162898.rtpl.php on line 93


Using shaarli 0.10.2, material 0.10.2-patch.3, with php 7.0.33 on a debian stretch.

I don't have these error messages with the default theme.
If you need some other informations or me to test someting, just let me know.

**Comment by kalvn** [comment] 2019-01-25 12:34
Thanks for the additional info, I'll keep investigating.

**Comment by kalvn** [comment] 2019-01-25 12:44
@iGormilhit your error is really weird, there's not even a call to a function `thumbnail` in linklist template. At least not since the migration from v0.9 to v0.10.

Can you try to remove all files in directory `/var/www/shaarli/tmp/`?

**Comment by iGormilhit** [comment] 2019-01-25 12:49
@kalvn Ok. I did remove everything in `/var/www/shaarli/tmp` and still...:

[Fri Jan 25 13:47:35.790719 2019] [:error] [pid 4855] [client 85.195.214.254:47812] PHP Fatal error:  Uncaught Error: Call to undefined function thumbnail() in /var/www/shaarli/tmp/linklist.aeadca0864f49f08401fb0f97c162898.rtpl.php:93\nStack trace:\n#0 /var/www/shaarli/inc/rain.tpl.class.php(175): include()\n#1 /var/www/shaarli/application/PageBuilder.php(188): RainTPL->draw('linklist')\n#2 /var/www/shaarli/index.php(497): PageBuilder->renderPage('linklist')\n#3 /var/www/shaarli/index.php(1549): showLinkList(Object(PageBuilder), Object(LinkDB), Object(Shaarli\\Config\\ConfigManager), Object(PluginManager), Object(Shaarli\\Security\\LoginManager))\n#4 /var/www/shaarli/index.php(1866): renderPage(Object(Shaarli\\Config\\ConfigManager), Object(PluginManager), Object(LinkDB), Object(History), Object(Shaarli\\Security\\SessionManager), Object(Shaarli\\Security\\LoginManager))\n#5 {main}\n  thrown in /var/www/shaarli/tmp/linklist.aeadca0864f49f08401fb0f97c162898.rtpl.php on line 93

**Comment by iGormilhit** [comment] 2019-01-25 12:49
I can add that I've jumped some shaarli versions... Maybe I should make a fresh install.

**Comment by iGormilhit** [comment] 2019-01-25 12:54
@kalvn My bad. I deleted the `/var/www/shaarli/tpl/material` directory and reinstalled the material theme and I don't get the error message anymore. Sorry... :worried:

**Comment by kalvn** [comment] 2019-01-25 13:01
No problem @iGormilhit I'm glad it works now :)

**Comment by 14ngr15t** [comment] 2019-01-26 21:33
I'll test deleting that too and reinstalling the theme.  I am on a fresh
install of the latest version of Shaarli, not an upgrade.

Thanks for all the help!

**Comment by kalvn** [comment] 2019-02-24 15:01
@14ngr15t Is it ok if I close this issue now?

**Closed** 2019-03-10 14:31 UTC
Labels: bug, help wanted
