### ISSUE TITLE
Permalink page broken meta tag with unwanted output

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#88] opened 2018-11-05 19:13 UTC
Hi, the meta description tag's content output is not html stripped (or how it was before) and when I click on any timestamp to open just one shared link/story, the page is broken: 

![screenshot_20181105-200122](https://user-images.githubusercontent.com/21174107/48020382-131dbe00-e136-11e8-8321-23b03faae58e.jpg)

In the HTML source: 

![screenshot_20181105-200214](https://user-images.githubusercontent.com/21174107/48020485-4e1ff180-e136-11e8-8c4b-800cb47f635f.jpg)

Now I'm on mobile but I think it's not a mobile related issue.

You might be able to reproduce it, just share a link without any further changes but add some text to the long description (some words are enough, no need for a paragraph). I also have the markdown plugin enabled. This was working fine before the latest theme update.

**Comment by nicolasdanelon** [comment] 2018-11-05 19:16
and this code is commented in the home page
![Uploading Screenshot from 2018-11-05 16-15-35.png…]()

**Comment by nicolasdanelon** [comment] 2018-11-05 19:17
And this commented timestamp is only the home page

![screenshot from 2018-11-05 16-15-35](https://user-images.githubusercontent.com/2846046/48021019-36387580-e116-11e8-8649-600aff4a4b04.png)

**Comment by kalvn** [comment] 2018-11-05 19:54
Can you help me to reproduce?

I did pretty much as you did: create a link with a long description and with the Markdown plugin enabled. But when I check this meta tag, I don't have HTML at the beginning.

Can you tell me which plugins you use?

@nicolasdanelon This will be fixed with the next commit.

**Comment by plexa** [comment] 2018-11-05 21:41
I'm facing same issue. See example -> https://lebrade.dedyn.io/?z1Q9RA . How can I assist you?

**Comment by kalvn** [comment] 2018-11-05 21:54
Do you have the same issue with default theme?

Do you use plugins listed on screenshot above?

**Comment by plexa** [comment] 2018-11-05 21:58
1. no, with default theme there is no issue!
2. 2 plugins: markdown toolbar and markdown, nothing else.

**Comment by plexa** [comment] 2018-11-05 22:02
3. the related plugin is markdown! (deactivated markdown toolbar, issue remained)

**Comment by immanuelfodor** [comment] 2018-11-06 04:10
I think PHP strip_tags is what we need here, almost the same problem and the first answer solves it for them: https://stackoverflow.com/questions/14684077/remove-all-html-tags-from-php-string

**Comment by kalvn** [comment] 2018-11-06 09:30
Okay I was able to reproduce with a fresh installation. That's indeed related to the markdown plugin that injects HTML in link descriptions. The reason why it doesn't happen on the default theme is that the *og* tags are completely skipped, not sure why. I'll open an issue on Shaarli repo to investigate.

`stip_tags` should indeed solve the issue. I'll do a commit today.

**Comment by kalvn** [comment] 2018-11-06 19:33
There you go @immanuelfodor https://github.com/kalvn/Shaarli-Material/commit/21c05a31c6af3f5b3e1800743a03bd4a66b3542a

**Closed by kalvn** 2018-11-06 19:33 UTC
Labels: bug, help wanted

**Comment by immanuelfodor** [comment] 2018-11-07 03:52
Wonderful, now works without problem, thank you!
